Zone improvements
lambdaclass/lambda_backend_game_engine pull request #31
Opened 2023-11-03 18:40 UTC by AminArria

- Zone effect is only applied once, before it was applied on each zone tick (😱 )
- Zone center is selected at random, before it was hardcoded to `(0, 0)`

2023-11-03 20:50 UTC, ncontinanza commented
Looking good! Just a detail I found out while testing on the client, depending on the value of the random center it may happen that when the match starts there's a small region of the map where the damage zone is active.

<img width="891" alt="image" src="https://github.com/lambdaclass/lambda_backend_game_engine/assets/17294394/8446e7d2-47ea-498e-8c9a-96e4c6fb055d">

2023-11-03 20:52 UTC, ncontinanza requested changes
Looking good! Just a detail I found out while testing on the client, depending on the value of the random center it may happen that when the match starts there's a small region of the map where the damage zone is active. We should change the initial values or the radius in order to make sure that the whole map is always clear at the beginning.

<img width="891" alt="image" src="https://github.com/lambdaclass/lambda_backend_game_engine/assets/17294394/8446e7d2-47ea-498e-8c9a-96e4c6fb055d">

2023-11-06 18:22 UTC, AminArria commented
@ncontinanza I've made the corresponding change in CoM due to config coming from there now

2023-11-06 18:28 UTC, ncontinanza approved these changes

2023-11-06 18:28 UTC, merged